'use client';

import React, { useState, useEffect, useRef } from 'react';
import {
  TrendingUp,
  Shield,
  Zap,
  BarChart3,
  Brain,
  CheckCircle,
  ArrowRight,
  Menu,
  X,
  ChevronDown,
  Globe,
  Database,
  Cpu,
  Wallet,
  Activity,
  Link
} from 'lucide-react';

// --- Custom Hooks ---

// Hook for intersection observer (scroll animations)
const useOnScreen = (options) => {
  const ref = useRef(null);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) {
        setIsVisible(true);
        observer.disconnect();
      }
    }, options);

    if (ref.current) {
      observer.observe(ref.current);
    }

    return () => {
      if (ref.current) observer.unobserve(ref.current);
    };
  }, [ref, options]);

  return [ref, isVisible];
};

// Hook for animated numbers
const AnimatedCounter = ({ end, duration = 2000, suffix = '', decimals = 0 }) => {
  const [count, setCount] = useState(0);
  const [ref, isVisible] = useOnScreen({ threshold: 0.5 });

  useEffect(() => {
    if (!isVisible) return;

    let startTime;
    let animationFrame;

    const step = (timestamp) => {
      if (!startTime) startTime = timestamp;
      const progress = Math.min((timestamp - startTime) / duration, 1);

      setCount(progress * end);

      if (progress < 1) {
        animationFrame = window.requestAnimationFrame(step);
      }
    };

    animationFrame = window.requestAnimationFrame(step);
    return () => window.cancelAnimationFrame(animationFrame);
  }, [end, duration, isVisible]);

  return (
    <span ref={ref} className="tabular-nums">
      {count.toFixed(decimals)}{suffix}
    </span>
  );
};

// --- Data ---

// Reordered: Low -> Moderate -> High Risk
const STRATEGIES = [
  {
    id: 2,
    name: "Delta Neutral Core",
    type: "Conservative",
    description: "Market-neutral strategy harvesting funding rates and spot-future arbitrage.",
    apy: 24.8,
    winRate: 92,
    risk: "Low",
    minInv: "1,000",
    assets: ["USDT", "USDC"]
  },
  {
    id: 3,
    name: "Trend Surfer XL",
    type: "Moderate",
    description: "AI-driven trend following that identifies macro shifts using on-chain metrics.",
    apy: 65.2,
    winRate: 55,
    risk: "Medium",
    minInv: "250",
    assets: ["ALT", "L2s"]
  },
  {
    id: 1,
    name: "Alpha Predator",
    type: "Aggressive",
    description: "High-frequency scalping utilizing order book imbalances and volatility spikes.",
    apy: 142.5,
    winRate: 68,
    risk: "High",
    minInv: "500",
    assets: ["BTC", "ETH", "SOL"]
  }
];

const FAQS = [
  {
    q: "Do I need to provide API keys?",
    a: "No. We utilize a direct, secure OAuth connection with OKX. You simply log in to your exchange account to authorize the strategy. No manual handling of API keys is required."
  },
  {
    q: "Is my capital safe?",
    a: "Yes. Since the connection utilizes 'Trade Only' permissions by default, we cannot touch your funds. Additionally, our strategies have built-in stop-losses and risk management protocols."
  },
  {
    q: "Can I run multiple strategies at once?",
    a: "Absolutely. You can allocate different portions of your portfolio to different strategies directly from your dashboard to diversify your risk exposure."
  },
  {
    q: "What is the cost?",
    a: "We operate on a profit-sharing model. There is no monthly fee. We take a small percentage of the profits generated by the AI, ensuring our incentives are perfectly aligned with yours."
  }
];

// --- Components ---

const Button = ({ children, variant = 'primary', className = '', ...props }) => {
  const baseStyle = "px-6 py-3 rounded-lg font-semibold transition-all duration-300 flex items-center justify-center gap-2";
  const variants = {
    primary: "bg-[#00D9FF] text-[#0A0E1A] hover:bg-[#00b8d9] hover:shadow-[0_0_20px_rgba(0,217,255,0.4)]",
    outline: "border border-[#00D9FF] text-[#00D9FF] hover:bg-[#00D9FF]/10",
    glow: "bg-gradient-to-r from-[#00D9FF] to-[#00D4AA] text-[#0A0E1A] hover:opacity-90 hover:shadow-[0_0_30px_rgba(0,212,170,0.4)]"
  };

  return (
    <button className={`${baseStyle} ${variants[variant]} ${className}`} {...props}>
      {children}
    </button>
  );
};

const SectionTitle = ({ title, subtitle, align = 'center' }) => (
  <div className={`mb-16 ${align === 'center' ? 'text-center' : 'text-left'}`}>
    <h2 className="text-3xl md:text-5xl font-bold text-white mb-4 tracking-tight">
      {title}
    </h2>
    <div className={`h-1 w-20 bg-gradient-to-r from-[#00D9FF] to-[#00D4AA] mb-6 ${align === 'center' ? 'mx-auto' : ''}`}></div>
    <p className="text-gray-400 text-lg max-w-2xl mx-auto leading-relaxed">
      {subtitle}
    </p>
  </div>
);

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 50);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <nav className={`fixed w-full z-50 transition-all duration-300 ${scrolled ? 'bg-[#0A0E1A]/90 backdrop-blur-md border-b border-white/10 py-4' : 'bg-transparent py-6'}`}>
      <div className="container mx-auto px-6 flex justify-between items-center">
        <div className="text-2xl font-bold text-white tracking-wider flex items-center gap-2">
          <div className="w-8 h-8 bg-gradient-to-br from-[#00D9FF] to-[#00D4AA] rounded flex items-center justify-center">
            <Brain size={20} className="text-[#0A0E1A]" />
          </div>
          INSAI
        </div>

        {/* Desktop Menu */}
        <div className="hidden md:flex items-center gap-8">
          <a href="#performance" className="text-gray-300 hover:text-[#00D9FF] transition-colors">Performance</a>
          <a href="#strategies" className="text-gray-300 hover:text-[#00D9FF] transition-colors">Strategies</a>
          <a href="#how-it-works" className="text-gray-300 hover:text-[#00D9FF] transition-colors">How it Works</a>
          <Button variant="outline" className="!py-2 !px-4">Launch App</Button>
        </div>

        {/* Mobile Toggle */}
        <button className="md:hidden text-white" onClick={() => setIsOpen(!isOpen)}>
          {isOpen ? <X /> : <Menu />}
        </button>
      </div>

      {/* Mobile Menu */}
      {isOpen && (
        <div className="absolute top-full left-0 w-full bg-[#0A0E1A] border-b border-white/10 p-6 flex flex-col gap-4 md:hidden">
          <a href="#performance" className="text-gray-300 text-lg" onClick={() => setIsOpen(false)}>Performance</a>
          <a href="#strategies" className="text-gray-300 text-lg" onClick={() => setIsOpen(false)}>Strategies</a>
          <a href="#how-it-works" className="text-gray-300 text-lg" onClick={() => setIsOpen(false)}>How it Works</a>
          <Button className="w-full">Launch App</Button>
        </div>
      )}
    </nav>
  );
};

const Hero = () => {
  // Animation state for the chart path
  const [pathLength, setPathLength] = useState(0);
  const pathRef = useRef(null);

  useEffect(() => {
    if (pathRef.current) {
      setPathLength(pathRef.current.getTotalLength());
    }
  }, []);

  return (
    <section className="relative min-h-screen flex items-center pt-20 overflow-hidden">
      {/* Background Elements */}
      <div className="absolute top-0 left-0 w-full h-full bg-[#0A0E1A] z-0">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-[#00D9FF]/10 rounded-full blur-[128px]"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-[#00D4AA]/10 rounded-full blur-[128px]"></div>
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20"></div>
      </div>

      <div className="container mx-auto px-6 relative z-10 grid md:grid-cols-2 gap-12 items-center">
        <div className="space-y-8">

          <h1 className="text-5xl md:text-7xl font-bold text-white leading-tight">
            Institutional Grade <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#00D9FF] to-[#00D4AA]">
              AI Trading
            </span>
          </h1>

          <p className="text-gray-400 text-lg md:text-xl max-w-lg leading-relaxed">
            Leverage multi-source data feeds and transformer models to automate your trading on OKX. Professional tools, now for everyone.
          </p>

          <div className="flex flex-col sm:flex-row gap-4">
            <Button variant="glow">Start Trading Now <ArrowRight size={18} /></Button>
            <Button variant="outline">View Live Demo</Button>
          </div>

          <div className="grid grid-cols-3 gap-8 pt-8 border-t border-white/10">
            <div>
              <div className="text-3xl font-bold text-white mb-1">
                <AnimatedCounter end={500} suffix="M+" />
              </div>
              <div className="text-sm text-gray-500">Volume Traded</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-[#00D4AA] mb-1">
                <AnimatedCounter end={142} suffix="%" />
              </div>
              <div className="text-sm text-gray-500">Top APY</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-white mb-1">
                <AnimatedCounter end={10} suffix="k+" />
              </div>
              <div className="text-sm text-gray-500">Active Users</div>
            </div>
          </div>
        </div>

        <div className="relative hidden md:block">
          {/* Abstract Dashboard Mockup */}
          <div className="relative z-10 bg-[#131826] border border-white/10 rounded-2xl p-6 shadow-2xl transform rotate-y-12 rotate-x-6 hover:rotate-0 transition-all duration-700">
            <div className="flex justify-between items-center mb-6 border-b border-white/5 pb-4">
              <div className="flex gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500"></div>
                <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                <div className="w-3 h-3 rounded-full bg-green-500"></div>
              </div>
              <div className="text-gray-500 text-xs font-mono">INSAI_TERMINAL_V1.4</div>
            </div>

            <div className="space-y-4">
              <div className="flex justify-between items-end">
                <div>
                  <div className="text-gray-400 text-sm mb-1">Total Balance</div>
                  <div className="text-4xl font-bold text-white">
                    $<AnimatedCounter end={24592.84} decimals={2} duration={1500} />
                  </div>
                </div>
                <div className="text-[#00D4AA] text-sm bg-[#00D4AA]/10 px-2 py-1 rounded flex items-center gap-1">
                  +12.4% (24h)
                </div>
              </div>

              {/* Live Animated Chart Area */}
              <div className="h-48 bg-gradient-to-b from-[#00D9FF]/5 to-transparent rounded-lg border border-[#00D9FF]/10 relative overflow-hidden">
                <svg className="w-full h-full" viewBox="0 0 300 200" preserveAspectRatio="none">
                  <defs>
                    <linearGradient id="gradient" x1="0%" y1="0%" x2="0%" y2="100%">
                      <stop offset="0%" stopColor="#00D9FF" stopOpacity="0.5" />
                      <stop offset="100%" stopColor="#00D9FF" stopOpacity="0" />
                    </linearGradient>
                  </defs>
                  {/* Static fill for background */}
                  <path d="M0,100 C50,80 100,120 150,60 C200,20 250,40 300,10 L300,200 L0,200 Z" fill="url(#gradient)" opacity="0.4" />

                  {/* Animated Line */}
                  <path
                    ref={pathRef}
                    d="M0,100 C50,80 100,120 150,60 C200,20 250,40 300,10"
                    stroke="#00D9FF"
                    strokeWidth="3"
                    fill="none"
                    strokeDasharray={pathLength}
                    strokeDashoffset={pathLength}
                    className="animate-[draw_3s_ease-out_forwards]"
                  />

                  {/* Pulse Effect at the end tip */}
                  <circle cx="100%" cy="5%" r="4" fill="#00D4AA" className="animate-ping opacity-75" style={{ transformBox: 'fill-box' }} />
                  <circle cx="100%" cy="5%" r="2" fill="#00D4AA" />
                </svg>
                <style>{`
                  @keyframes draw {
                    to {
                      stroke-dashoffset: 0;
                    }
                  }
                `}</style>
              </div>

              <div className="grid grid-cols-2 gap-4">
                 <div className="bg-white/5 p-3 rounded text-xs">
                    <div className="text-gray-500 mb-1">Active Bot</div>
                    <div className="text-white font-semibold">Alpha Predator</div>
                 </div>
                 <div className="bg-white/5 p-3 rounded text-xs">
                    <div className="text-gray-500 mb-1">Status</div>
                    <div className="text-[#00D4AA] font-semibold flex items-center gap-1"><div className="w-2 h-2 rounded-full bg-[#00D4AA] animate-pulse"></div> Running</div>
                 </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

const Strategies = () => {
  return (
    <section id="strategies" className="py-12 md:py-24 bg-[#0A0E1A] relative overflow-hidden">
      {/* Subtle background element */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-[#00D9FF]/5 rounded-full blur-[120px] pointer-events-none"></div>

      <div className="container mx-auto px-4 md:px-6 relative z-10">
        <div className="text-center mb-12 md:mb-16">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4 tracking-tight">
            Intelligent Strategies
          </h2>
          <div className="h-1 w-20 bg-gradient-to-r from-[#00D9FF] to-[#00D4AA] mb-6 mx-auto"></div>
          <p className="text-gray-400 text-base md:text-lg max-w-2xl mx-auto leading-relaxed">
            Choose the AI model that fits your risk appetite. Each strategy utilizes distinct data sets and execution parameters.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-6 lg:gap-8 max-w-7xl mx-auto">
          {STRATEGIES.map((strat, idx) => (
            <div
              key={strat.id}
              className="group relative bg-gradient-to-b from-[#131826] to-[#0D1219] rounded-2xl border border-white/10 overflow-hidden hover:border-[#00D9FF]/40 transition-all duration-500 hover:shadow-2xl hover:shadow-[#00D9FF]/10"
              style={{ animationDelay: `${idx * 100}ms` }}
            >
              {/* Top accent bar */}
              <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-[#00D9FF] to-[#00D4AA] transform scale-x-0 group-hover:scale-x-100 transition-transform duration-500 origin-left"></div>

              {/* Card content */}
              <div className="p-6 md:p-8">
                {/* Header */}
                <div className="flex items-start justify-between mb-6">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#00D9FF]/20 to-[#00D4AA]/20 border border-[#00D9FF]/30 flex items-center justify-center text-[#00D9FF] group-hover:scale-110 transition-transform duration-300">
                      {strat.id === 1 ? <Zap size={20} /> : strat.id === 2 ? <Shield size={20} /> : <TrendingUp size={20} />}
                    </div>
                  </div>
                  <span className={`text-[10px] font-bold px-2.5 py-1 rounded-md uppercase tracking-wider ${
                    strat.risk === 'High' ? 'bg-orange-500/10 text-orange-400 border border-orange-500/20' :
                    strat.risk === 'Low' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' :
                    'bg-amber-500/10 text-amber-400 border border-amber-500/20'
                  }`}>
                    {strat.risk} Risk
                  </span>
                </div>

                {/* Title & Description */}
                <h3 className="text-xl md:text-2xl font-bold text-white mb-3 group-hover:text-[#00D9FF] transition-colors duration-300">
                  {strat.name}
                </h3>
                <p className="text-gray-400 text-sm leading-relaxed mb-6 min-h-[60px]">
                  {strat.description}
                </p>

                {/* Metrics Grid */}
                <div className="grid grid-cols-2 gap-3 mb-6 pb-6 border-b border-white/5">
                  <div className="space-y-1">
                    <div className="text-xs text-gray-500 uppercase tracking-wider font-medium">Est. APY</div>
                    <div className="text-2xl font-bold bg-gradient-to-r from-[#00D9FF] to-[#00D4AA] bg-clip-text text-transparent">
                      {strat.apy}%
                    </div>
                  </div>
                  <div className="space-y-1">
                    <div className="text-xs text-gray-500 uppercase tracking-wider font-medium">Win Rate</div>
                    <div className="text-2xl font-bold text-white">{strat.winRate}%</div>
                  </div>
                </div>

                {/* Details */}
                <div className="space-y-2.5 mb-6">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-gray-500">Min. Investment</span>
                    <span className="text-white font-semibold">${strat.minInv}</span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-gray-500">Assets</span>
                    <span className="text-white font-semibold">{strat.assets.join(', ')}</span>
                  </div>
                </div>

                {/* CTA Button */}
                <button className="w-full py-3 rounded-lg font-semibold transition-all duration-300 border-2 border-[#00D9FF]/30 text-[#00D9FF] hover:bg-[#00D9FF] hover:text-[#0A0E1A] hover:border-[#00D9FF] hover:shadow-lg hover:shadow-[#00D9FF]/20">
                  Subscribe
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

const AIProcess = () => {
  return (
    <section id="technology" className="py-24 relative overflow-hidden bg-[#0D1220]">
       {/* Decorative grids */}
       <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:64px_64px]"></div>

      <div className="container mx-auto px-6 relative z-10">
        <SectionTitle
          title="The AI Architecture"
          subtitle="How INSAI turns raw noise into profitable signals within milliseconds."
        />

        {/* Waterfall / Process Flow */}
        <div className="max-w-4xl mx-auto">

          {/* Layer 1: Input */}
          <div className="grid md:grid-cols-3 gap-4 mb-12">
            <div className="bg-[#1A2133] p-6 rounded-xl border border-white/5 text-center group hover:border-[#00D9FF]/40 transition-all">
              <Globe className="mx-auto text-[#00D9FF] mb-4 group-hover:scale-110 transition-transform" size={32} />
              <h4 className="text-white font-semibold mb-2">Global Sentiment</h4>
              <p className="text-xs text-gray-400">News APIs, Twitter/X Social Volume, Fear & Greed Index</p>
            </div>
            <div className="bg-[#1A2133] p-6 rounded-xl border border-white/5 text-center group hover:border-[#00D9FF]/40 transition-all">
              <Database className="mx-auto text-[#00D9FF] mb-4 group-hover:scale-110 transition-transform" size={32} />
              <h4 className="text-white font-semibold mb-2">On-Chain Data</h4>
              <p className="text-xs text-gray-400">Whale Alerts, Exchange Inflows, Liquidation Maps</p>
            </div>
            <div className="bg-[#1A2133] p-6 rounded-xl border border-white/5 text-center group hover:border-[#00D9FF]/40 transition-all">
              <BarChart3 className="mx-auto text-[#00D9FF] mb-4 group-hover:scale-110 transition-transform" size={32} />
              <h4 className="text-white font-semibold mb-2">Price Action</h4>
              <p className="text-xs text-gray-400">Order Book Imbalance, Technical Indicators, Volatility</p>
            </div>
          </div>

          {/* Connector Arrows */}
          <div className="flex justify-center gap-16 md:gap-32 mb-4 text-gray-600">
             <div className="h-16 w-[1px] bg-gradient-to-b from-[#00D9FF]/50 to-transparent"></div>
             <div className="h-16 w-[1px] bg-gradient-to-b from-[#00D9FF]/50 to-transparent"></div>
             <div className="h-16 w-[1px] bg-gradient-to-b from-[#00D9FF]/50 to-transparent"></div>
          </div>

          {/* Layer 2: The Brain */}
          <div className="relative bg-gradient-to-r from-[#00D9FF]/10 to-[#00D4AA]/10 p-[1px] rounded-2xl mb-12 mx-auto max-w-2xl">
            <div className="bg-[#131826] rounded-2xl p-8 text-center relative overflow-hidden">
               <div className="absolute inset-0 bg-[#00D9FF]/5 animate-pulse"></div>
               <Brain className="mx-auto text-white mb-4 relative z-10" size={48} />
               <h3 className="text-2xl font-bold text-white mb-2 relative z-10">Neural Processing Core</h3>
               <p className="text-gray-400 text-sm relative z-10">
                 Transformer models analyze correlations across 50+ data points to calculate probability scores for potential trade setups.
               </p>
            </div>
          </div>

          {/* Connector Single */}
           <div className="flex justify-center mb-4">
             <div className="h-16 w-[1px] bg-gradient-to-b from-[#00D4AA] to-transparent"></div>
          </div>

          {/* Layer 3: Execution */}
          <div className="bg-[#0A0E1A] border border-[#00D4AA]/30 rounded-xl p-6 max-w-md mx-auto flex items-center gap-6">
            <div className="bg-white p-2 rounded">
              {/* Simple text logo for OKX */}
              <div className="font-black text-black text-lg tracking-tighter">OKX</div>
            </div>
            <div className="flex-1">
              <h4 className="text-white font-bold">Execution Engine</h4>
              <p className="text-xs text-gray-400">API signals sent instantly to your OKX account for execution.</p>
            </div>
            <div className="w-3 h-3 bg-[#00D4AA] rounded-full animate-ping"></div>
          </div>

        </div>
      </div>
    </section>
  );
};

const Performance = () => {
  return (
    <section id="performance" className="py-12 md:py-24 bg-[#0D1220] relative overflow-hidden">
      {/* Background grid pattern */}
      <div className="absolute inset-0 bg-[linear-gradient(rgba(0,217,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(0,217,255,0.03)_1px,transparent_1px)] bg-[size:64px_64px]"></div>

      <div className="container mx-auto px-4 md:px-6 relative z-10">
        <div className="mb-8 md:mb-12">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4 tracking-tight">Live Performance</h2>
          <div className="h-1 w-16 md:w-20 bg-gradient-to-r from-[#00D9FF] to-[#00D4AA] mb-4"></div>
          <p className="text-gray-400 text-base md:text-lg">Real-time tracking of all active AI strategies.</p>
        </div>

        {/* Table Container with border */}
        <div className="bg-[#131826] rounded-xl md:rounded-2xl border border-white/10 overflow-hidden shadow-2xl">
          {/* Horizontal scroll container with scroll hint */}
          <div className="overflow-x-auto scrollbar-thin scrollbar-thumb-[#00D9FF]/20 scrollbar-track-transparent">
            <table className="w-full border-collapse min-w-[900px]">
              <thead>
                <tr className="text-gray-500 text-xs uppercase tracking-wider border-b-2 border-[#00D9FF]/20 bg-gradient-to-b from-black/30 to-black/10">
                  <th className="px-4 md:px-6 py-4 md:py-5 text-left font-bold whitespace-nowrap">Strategy</th>
                  <th className="px-4 md:px-6 py-4 md:py-5 text-center font-bold whitespace-nowrap">AI Model</th>
                  <th className="px-4 md:px-6 py-4 md:py-5 text-center font-bold whitespace-nowrap">Return (30D)</th>
                  <th className="px-4 md:px-6 py-4 md:py-5 text-center font-bold whitespace-nowrap">Sharpe Ratio</th>
                  <th className="px-4 md:px-6 py-4 md:py-5 text-center font-bold whitespace-nowrap">Max Drawdown</th>
                  <th className="px-4 md:px-6 py-4 md:py-5 text-center font-bold whitespace-nowrap">Win Rate</th>
                  <th className="px-4 md:px-6 py-4 md:py-5 text-center font-bold whitespace-nowrap">Total Trades</th>
                </tr>
              </thead>
              <tbody className="text-white divide-y divide-white/5">
                {[
                  {
                    name: "Alpha Momentum",
                    model: "ChatGPT-4",
                    return: "+156.7%",
                    sharpe: "2.84",
                    drawdown: "-12.3%",
                    winRate: "87%",
                    trades: "3,247",
                    active: true
                  },
                  {
                    name: "Steady Growth",
                    model: "Claude 3.5",
                    return: "+68.4%",
                    sharpe: "3.12",
                    drawdown: "-5.8%",
                    winRate: "91%",
                    trades: "1,842",
                    active: true
                  },
                  {
                    name: "Volatility Edge",
                    model: "Grok-2",
                    return: "+124.5%",
                    sharpe: "2.67",
                    drawdown: "-9.4%",
                    winRate: "85%",
                    trades: "4,521",
                    active: true
                  },
                ].map((row, idx) => (
                  <tr key={idx} className="group hover:bg-gradient-to-r hover:from-[#00D9FF]/5 hover:via-[#00D9FF]/3 hover:to-transparent transition-all duration-300 cursor-pointer">
                    <td className="px-4 md:px-6 py-5 md:py-6 text-left">
                      <div className="flex items-center gap-3">
                        <div className="hidden md:flex w-1 h-10 bg-gradient-to-b from-[#00D9FF] to-[#00D4AA] rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
                        <div>
                          <span className="font-bold text-sm md:text-base text-white whitespace-nowrap block">{row.name}</span>
                          <div className="flex items-center gap-1.5 mt-1">
                            <span className="w-1.5 h-1.5 bg-[#00D4AA] rounded-full animate-pulse"></span>
                            <span className="text-[10px] md:text-xs text-gray-500 uppercase tracking-wider">Active</span>
                          </div>
                        </div>
                      </div>
                    </td>
                    <td className="px-4 md:px-6 py-5 md:py-6 text-center">
                      <span className="inline-block px-2.5 md:px-3 py-1.5 md:py-2 rounded-full bg-[#00D9FF]/10 text-[#00D9FF] text-xs md:text-sm border border-[#00D9FF]/30 font-semibold whitespace-nowrap hover:bg-[#00D9FF]/20 hover:border-[#00D9FF]/50 transition-all duration-200">
                        {row.model}
                      </span>
                    </td>
                    <td className="px-4 md:px-6 py-5 md:py-6 text-center">
                      <span className={`font-bold text-base md:text-lg whitespace-nowrap ${row.return.startsWith('+') ? 'text-[#00D4AA]' : 'text-red-400'}`}>
                        {row.return}
                      </span>
                    </td>
                    <td className="px-4 md:px-6 py-5 md:py-6 text-center">
                      <span className="font-semibold text-sm md:text-base text-white">{row.sharpe}</span>
                    </td>
                    <td className="px-4 md:px-6 py-5 md:py-6 text-center">
                      <span className="font-semibold text-sm md:text-base text-gray-300">{row.drawdown}</span>
                    </td>
                    <td className="px-4 md:px-6 py-5 md:py-6 text-center">
                      <span className="font-semibold text-sm md:text-base text-[#00D9FF]">{row.winRate}</span>
                    </td>
                    <td className="px-4 md:px-6 py-5 md:py-6 text-center">
                      <span className="font-medium text-sm md:text-base text-gray-300">{row.trades}</span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Mobile scroll hint */}
          <div className="md:hidden flex items-center justify-center gap-2 py-3 text-xs text-gray-500 border-t border-white/5">
            <span>Swipe to see more</span>
            <ArrowRight size={12} className="animate-pulse" />
          </div>
        </div>
      </div>
    </section>
  );
};

const HowItWorks = () => {
  return (
    <section id="how-it-works" className="py-24 bg-[#0D1220]">
      <div className="container mx-auto px-6">
        <SectionTitle title="Start in 3 Minutes" subtitle="No coding required. Just connect and automate." />

        <div className="grid md:grid-cols-3 gap-8">
          {[
            { icon: Link, title: "1. Connect Exchange", desc: "Log in securely to your OKX account. Our system connects directly without requiring manual API key handling." },
            { icon: Activity, title: "2. Choose Strategy", desc: "Browse the marketplace and choose a strategy that matches your risk profile and asset preference." },
            { icon: Zap, title: "3. Subscribe & Start", desc: "Click subscribe, allocate your funds, and the AI will immediately begin executing trades." }
          ].map((step, idx) => (
            <div key={idx} className="relative p-8 rounded-2xl bg-[#131826] border border-white/5 z-10">
              <div className="absolute -top-4 -left-4 w-12 h-12 bg-[#00D9FF] text-[#0A0E1A] font-bold text-xl flex items-center justify-center rounded-xl shadow-lg shadow-cyan-500/20">
                {idx + 1}
              </div>
              <step.icon size={40} className="text-gray-600 mb-6 mt-2" />
              <h3 className="text-xl font-bold text-white mb-3">{step.title}</h3>
              <p className="text-gray-400 leading-relaxed">
                {step.desc}
              </p>
            </div>
          ))}
        </div>

        <div className="flex justify-center mt-12">
          <Button variant="glow" className="text-lg px-8 py-4">
            Subscribe Now <ArrowRight size={20} />
          </Button>
        </div>
      </div>
    </section>
  );
};

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  return (
    <section className="py-24 bg-[#0A0E1A]">
      <div className="container mx-auto px-6 max-w-3xl">
        <SectionTitle title="Frequently Asked Questions" />

        <div className="space-y-4">
          {FAQS.map((faq, idx) => (
            <div key={idx} className="bg-[#131826] rounded-xl overflow-hidden border border-white/5">
              <button
                className="w-full p-6 text-left flex justify-between items-center text-white font-medium hover:bg-white/5 transition-colors"
                onClick={() => setOpenIndex(openIndex === idx ? null : idx)}
              >
                {faq.q}
                <ChevronDown className={`transition-transform ${openIndex === idx ? 'rotate-180' : ''}`} />
              </button>
              <div className={`px-6 text-gray-400 leading-relaxed transition-all duration-300 ease-in-out overflow-hidden ${openIndex === idx ? 'max-h-48 pb-6 opacity-100' : 'max-h-0 opacity-0'}`}>
                {faq.a}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

const Footer = () => {
  return (
    <footer className="bg-[#05070D] border-t border-white/10 pt-16 pb-8">
      <div className="container mx-auto px-6">
        <div className="grid md:grid-cols-4 gap-12 mb-12">
          <div className="col-span-1 md:col-span-2">
            <div className="text-2xl font-bold text-white tracking-wider flex items-center gap-2 mb-6">
              <div className="w-8 h-8 bg-gradient-to-br from-[#00D9FF] to-[#00D4AA] rounded flex items-center justify-center">
                <Brain size={20} className="text-[#0A0E1A]" />
              </div>
              INSAI
            </div>
            <p className="text-gray-500 max-w-sm">
              Democratizing institutional-grade trading strategies through artificial intelligence. Built for OKX.
            </p>
          </div>

          <div>
            <h4 className="text-white font-bold mb-4">Platform</h4>
            <ul className="space-y-2 text-gray-500">
              <li><a href="#" className="hover:text-[#00D9FF]">Strategies</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">Pricing</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">Live Performance</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">API Documentation</a></li>
            </ul>
          </div>

          <div>
            <h4 className="text-white font-bold mb-4">Legal</h4>
            <ul className="space-y-2 text-gray-500">
              <li><a href="#" className="hover:text-[#00D9FF]">Terms of Service</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">Privacy Policy</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">Risk Disclaimer</a></li>
            </ul>
          </div>
        </div>

        <div className="border-t border-white/5 pt-8 text-center text-gray-600 text-sm">
          &copy; {new Date().getFullYear()} INSAI Trading Technologies. All rights reserved.
          <br className="md:hidden" /> Cryptocurrency trading involves high risk. Invest responsibly.
        </div>
      </div>
    </footer>
  );
};

// --- Main App ---

export default function App() {
  return (
    <div className="min-h-screen bg-[#0A0E1A] text-white font-sans selection:bg-[#00D9FF] selection:text-[#0A0E1A]">
      <Navbar />
      <main>
        <Hero />
        <Strategies />
        <Performance />
        <AIProcess />
        <HowItWorks />
        <FAQ />
      </main>
      <Footer />
    </div>
  );
}
