import React, { useState, useEffect, useRef } from 'react';
import {
  TrendingUp,
  Shield,
  Zap,
  BarChart3,
  Brain,
  CheckCircle,
  ArrowRight,
  Menu,
  X,
  ChevronDown,
  Globe,
  Database,
  Cpu,
  Wallet,
  Activity,
  Link
} from 'lucide-react';

// --- Custom Hooks ---

// Hook for intersection observer (scroll animations)
const useOnScreen = (options) => {
  const ref = useRef(null);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) {
        setIsVisible(true);
        observer.disconnect();
      }
    }, options);

    if (ref.current) {
      observer.observe(ref.current);
    }

    return () => {
      if (ref.current) observer.unobserve(ref.current);
    };
  }, [ref, options]);

  return [ref, isVisible];
};

// Hook for animated numbers
const AnimatedCounter = ({ end, duration = 2000, suffix = '', decimals = 0 }) => {
  const [count, setCount] = useState(0);
  const [ref, isVisible] = useOnScreen({ threshold: 0.5 });

  useEffect(() => {
    if (!isVisible) return;

    let startTime;
    let animationFrame;

    const step = (timestamp) => {
      if (!startTime) startTime = timestamp;
      const progress = Math.min((timestamp - startTime) / duration, 1);

      setCount(progress * end);

      if (progress < 1) {
        animationFrame = window.requestAnimationFrame(step);
      }
    };

    animationFrame = window.requestAnimationFrame(step);
    return () => window.cancelAnimationFrame(animationFrame);
  }, [end, duration, isVisible]);

  return (
    <span ref={ref} className="tabular-nums">
      {count.toFixed(decimals)}{suffix}
    </span>
  );
};

// --- Data ---

// Reordered: Low -> Moderate -> High Risk
const STRATEGIES = [
  {
    id: 2,
    name: "Delta Neutral Core",
    type: "Conservative",
    description: "Market-neutral strategy harvesting funding rates and spot-future arbitrage.",
    apy: 24.8,
    winRate: 92,
    risk: "Low",
    minInv: "1,000",
    assets: ["USDT", "USDC"]
  },
  {
    id: 3,
    name: "Trend Surfer XL",
    type: "Moderate",
    description: "AI-driven trend following that identifies macro shifts using on-chain metrics.",
    apy: 65.2,
    winRate: 55,
    risk: "Medium",
    minInv: "250",
    assets: ["ALT", "L2s"]
  },
  {
    id: 1,
    name: "Alpha Predator",
    type: "Aggressive",
    description: "High-frequency scalping utilizing order book imbalances and volatility spikes.",
    apy: 142.5,
    winRate: 68,
    risk: "High",
    minInv: "500",
    assets: ["BTC", "ETH", "SOL"]
  }
];

const FAQS = [
  {
    q: "Do I need to provide API keys?",
    a: "No. We utilize a direct, secure OAuth connection with OKX. You simply log in to your exchange account to authorize the strategy. No manual handling of API keys is required."
  },
  {
    q: "Is my capital safe?",
    a: "Yes. Since the connection utilizes 'Trade Only' permissions by default, we cannot touch your funds. Additionally, our strategies have built-in stop-losses and risk management protocols."
  },
  {
    q: "Can I run multiple strategies at once?",
    a: "Absolutely. You can allocate different portions of your portfolio to different strategies directly from your dashboard to diversify your risk exposure."
  },
  {
    q: "What is the cost?",
    a: "We operate on a profit-sharing model. There is no monthly fee. We take a small percentage of the profits generated by the AI, ensuring our incentives are perfectly aligned with yours."
  }
];

// --- Components ---

const Button = ({ children, variant = 'primary', className = '', ...props }) => {
  const baseStyle = "px-6 py-3 rounded-lg font-semibold transition-all duration-300 flex items-center justify-center gap-2";
  const variants = {
    primary: "bg-[#00D9FF] text-[#0A0E1A] hover:bg-[#00b8d9] hover:shadow-[0_0_20px_rgba(0,217,255,0.4)]",
    outline: "border border-[#00D9FF] text-[#00D9FF] hover:bg-[#00D9FF]/10",
    glow: "bg-gradient-to-r from-[#00D9FF] to-[#00D4AA] text-[#0A0E1A] hover:opacity-90 hover:shadow-[0_0_30px_rgba(0,212,170,0.4)]"
  };

  return (
    <button className={`${baseStyle} ${variants[variant]} ${className}`} {...props}>
      {children}
    </button>
  );
};

const SectionTitle = ({ title, subtitle, align = 'center' }) => (
  <div className={`mb-16 ${align === 'center' ? 'text-center' : 'text-left'}`}>
    <h2 className="text-3xl md:text-5xl font-bold text-white mb-4 tracking-tight">
      {title}
    </h2>
    <div className={`h-1 w-20 bg-gradient-to-r from-[#00D9FF] to-[#00D4AA] mb-6 ${align === 'center' ? 'mx-auto' : ''}`}></div>
    <p className="text-gray-400 text-lg max-w-2xl mx-auto leading-relaxed">
      {subtitle}
    </p>
  </div>
);

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 50);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <nav className={`fixed w-full z-50 transition-all duration-300 ${scrolled ? 'bg-[#0A0E1A]/90 backdrop-blur-md border-b border-white/10 py-4' : 'bg-transparent py-6'}`}>
      <div className="container mx-auto px-6 flex justify-between items-center">
        <div className="text-2xl font-bold text-white tracking-wider flex items-center gap-2">
          <div className="w-8 h-8 bg-gradient-to-br from-[#00D9FF] to-[#00D4AA] rounded flex items-center justify-center">
            <Brain size={20} className="text-[#0A0E1A]" />
          </div>
          INSAI
        </div>

        {/* Desktop Menu */}
        <div className="hidden md:flex items-center gap-8">
          <a href="#performance" className="text-gray-300 hover:text-[#00D9FF] transition-colors">Performance</a>
          <a href="#strategies" className="text-gray-300 hover:text-[#00D9FF] transition-colors">Strategies</a>
          <a href="#how-it-works" className="text-gray-300 hover:text-[#00D9FF] transition-colors">How it Works</a>
          <Button variant="outline" className="!py-2 !px-4">Launch App</Button>
        </div>

        {/* Mobile Toggle */}
        <button className="md:hidden text-white" onClick={() => setIsOpen(!isOpen)}>
          {isOpen ? <X /> : <Menu />}
        </button>
      </div>

      {/* Mobile Menu */}
      {isOpen && (
        <div className="absolute top-full left-0 w-full bg-[#0A0E1A] border-b border-white/10 p-6 flex flex-col gap-4 md:hidden">
          <a href="#performance" className="text-gray-300 text-lg" onClick={() => setIsOpen(false)}>Performance</a>
          <a href="#strategies" className="text-gray-300 text-lg" onClick={() => setIsOpen(false)}>Strategies</a>
          <a href="#how-it-works" className="text-gray-300 text-lg" onClick={() => setIsOpen(false)}>How it Works</a>
          <Button className="w-full">Launch App</Button>
        </div>
      )}
    </nav>
  );
};

const Hero = () => {
  // Animation state for the chart path
  const [pathLength, setPathLength] = useState(0);
  const pathRef = useRef(null);

  useEffect(() => {
    if (pathRef.current) {
      setPathLength(pathRef.current.getTotalLength());
    }
  }, []);

  return (
    <section className="relative min-h-screen flex items-center pt-20 overflow-hidden">
      {/* Background Elements */}
      <div className="absolute top-0 left-0 w-full h-full bg-[#0A0E1A] z-0">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-[#00D9FF]/10 rounded-full blur-[128px]"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-[#00D4AA]/10 rounded-full blur-[128px]"></div>
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20"></div>
      </div>

      <div className="container mx-auto px-6 relative z-10 grid md:grid-cols-2 gap-12 items-center">
        <div className="space-y-8">

          <h1 className="text-5xl md:text-7xl font-bold text-white leading-tight">
            Institutional Grade <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#00D9FF] to-[#00D4AA]">
              AI Trading
            </span>
          </h1>

          <p className="text-gray-400 text-lg md:text-xl max-w-lg leading-relaxed">
            Leverage multi-source data feeds and transformer models to automate your trading on OKX. Professional tools, now for everyone.
          </p>

          <div className="flex flex-col sm:flex-row gap-4">
            <Button variant="glow">Start Trading Now <ArrowRight size={18} /></Button>
            <Button variant="outline">View Live Demo</Button>
          </div>

          <div className="grid grid-cols-3 gap-8 pt-8 border-t border-white/10">
            <div>
              <div className="text-3xl font-bold text-white mb-1">
                <AnimatedCounter end={500} suffix="M+" />
              </div>
              <div className="text-sm text-gray-500">Volume Traded</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-[#00D4AA] mb-1">
                <AnimatedCounter end={142} suffix="%" />
              </div>
              <div className="text-sm text-gray-500">Top APY</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-white mb-1">
                <AnimatedCounter end={10} suffix="k+" />
              </div>
              <div className="text-sm text-gray-500">Active Users</div>
            </div>
          </div>
        </div>

        <div className="relative hidden md:block">
          {/* Abstract Dashboard Mockup */}
          <div className="relative z-10 bg-[#131826] border border-white/10 rounded-2xl p-6 shadow-2xl transform rotate-y-12 rotate-x-6 hover:rotate-0 transition-all duration-700">
            <div className="flex justify-between items-center mb-6 border-b border-white/5 pb-4">
              <div className="flex gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500"></div>
                <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                <div className="w-3 h-3 rounded-full bg-green-500"></div>
              </div>
              <div className="text-gray-500 text-xs font-mono">INSAI_TERMINAL_V1.4</div>
            </div>

            <div className="space-y-4">
              <div className="flex justify-between items-end">
                <div>
                  <div className="text-gray-400 text-sm mb-1">Total Balance</div>
                  <div className="text-4xl font-bold text-white">
                    $<AnimatedCounter end={24592.84} decimals={2} duration={1500} />
                  </div>
                </div>
                <div className="text-[#00D4AA] text-sm bg-[#00D4AA]/10 px-2 py-1 rounded flex items-center gap-1">
                  +12.4% (24h)
                </div>
              </div>

              {/* Live Animated Chart Area */}
              <div className="h-48 bg-gradient-to-b from-[#00D9FF]/5 to-transparent rounded-lg border border-[#00D9FF]/10 relative overflow-hidden">
                <svg className="w-full h-full" viewBox="0 0 300 200" preserveAspectRatio="none">
                  <defs>
                    <linearGradient id="gradient" x1="0%" y1="0%" x2="0%" y2="100%">
                      <stop offset="0%" stopColor="#00D9FF" stopOpacity="0.5" />
                      <stop offset="100%" stopColor="#00D9FF" stopOpacity="0" />
                    </linearGradient>
                  </defs>
                  {/* Static fill for background */}
                  <path d="M0,100 C50,80 100,120 150,60 C200,20 250,40 300,10 L300,200 L0,200 Z" fill="url(#gradient)" opacity="0.4" />

                  {/* Animated Line */}
                  <path
                    ref={pathRef}
                    d="M0,100 C50,80 100,120 150,60 C200,20 250,40 300,10"
                    stroke="#00D9FF"
                    strokeWidth="3"
                    fill="none"
                    strokeDasharray={pathLength}
                    strokeDashoffset={pathLength}
                    className="animate-[draw_3s_ease-out_forwards]"
                  />

                  {/* Pulse Effect at the end tip */}
                  <circle cx="100%" cy="5%" r="4" fill="#00D4AA" className="animate-ping opacity-75" style={{ transformBox: 'fill-box' }} />
                  <circle cx="100%" cy="5%" r="2" fill="#00D4AA" />
                </svg>
                <style>{`
                  @keyframes draw {
                    to {
                      stroke-dashoffset: 0;
                    }
                  }
                `}</style>
              </div>

              <div className="grid grid-cols-2 gap-4">
                 <div className="bg-white/5 p-3 rounded text-xs">
                    <div className="text-gray-500 mb-1">Active Bot</div>
                    <div className="text-white font-semibold">Alpha Predator</div>
                 </div>
                 <div className="bg-white/5 p-3 rounded text-xs">
                    <div className="text-gray-500 mb-1">Status</div>
                    <div className="text-[#00D4AA] font-semibold flex items-center gap-1"><div className="w-2 h-2 rounded-full bg-[#00D4AA] animate-pulse"></div> Running</div>
                 </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

const Strategies = () => {
  return (
    <section id="strategies" className="py-24 bg-[#0A0E1A]">
      <div className="container mx-auto px-6">
        <SectionTitle
          title="Intelligent Strategies"
          subtitle="Choose the AI model that fits your risk appetite. Each strategy utilizes distinct data sets and execution parameters."
        />

        <div className="grid md:grid-cols-3 gap-8">
          {STRATEGIES.map((strat) => (
            <div key={strat.id} className="group relative bg-[#131826] rounded-2xl border border-white/5 p-8 hover:border-[#00D9FF]/30 transition-all duration-300 hover:-translate-y-2">
              <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-[#00D9FF] to-[#00D4AA] opacity-0 group-hover:opacity-100 transition-opacity rounded-t-2xl"></div>

              <div className="flex justify-between items-start mb-6">
                <div className="bg-white/5 p-3 rounded-lg text-[#00D9FF]">
                  {strat.id === 1 ? <Zap size={24} /> : strat.id === 2 ? <Shield size={24} /> : <TrendingUp size={24} />}
                </div>
                <span className={`text-xs font-semibold px-3 py-1 rounded-full ${
                  strat.risk === 'High' ? 'bg-red-500/10 text-red-400' :
                  strat.risk === 'Low' ? 'bg-green-500/10 text-green-400' :
                  'bg-yellow-500/10 text-yellow-400'
                }`}>
                  {strat.risk} Risk
                </span>
              </div>

              <h3 className="text-2xl font-bold text-white mb-2">{strat.name}</h3>
              <p className="text-gray-400 text-sm mb-6 min-h-[60px]">{strat.description}</p>

              <div className="grid grid-cols-2 gap-4 mb-8">
                <div className="bg-black/20 p-3 rounded text-center">
                  <div className="text-2xl font-bold text-[#00D4AA]">{strat.apy}%</div>
                  <div className="text-xs text-gray-500">Est. APY</div>
                </div>
                <div className="bg-black/20 p-3 rounded text-center">
                  <div className="text-2xl font-bold text-white">{strat.winRate}%</div>
                  <div className="text-xs text-gray-500">Win Rate</div>
                </div>
              </div>

              <ul className="space-y-3 mb-8">
                <li className="flex items-center gap-2 text-sm text-gray-300">
                  <CheckCircle size={14} className="text-[#00D9FF]" /> Min. Invest: ${strat.minInv}
                </li>
                <li className="flex items-center gap-2 text-sm text-gray-300">
                  <CheckCircle size={14} className="text-[#00D9FF]" /> Assets: {strat.assets.join(', ')}
                </li>
              </ul>

              <Button variant="outline" className="w-full group-hover:bg-[#00D9FF] group-hover:text-[#0A0E1A]">
                Subscribe
              </Button>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

const AIProcess = () => {
  return (
    <section id="technology" className="py-24 relative overflow-hidden bg-[#0D1220]">
       {/* Decorative grids */}
       <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:64px_64px]"></div>

      <div className="container mx-auto px-6 relative z-10">
        <SectionTitle
          title="The AI Architecture"
          subtitle="How INSAI turns raw noise into profitable signals within milliseconds."
        />

        {/* Waterfall / Process Flow */}
        <div className="max-w-4xl mx-auto">

          {/* Layer 1: Input */}
          <div className="grid md:grid-cols-3 gap-4 mb-12">
            <div className="bg-[#1A2133] p-6 rounded-xl border border-white/5 text-center group hover:border-[#00D9FF]/40 transition-all">
              <Globe className="mx-auto text-[#00D9FF] mb-4 group-hover:scale-110 transition-transform" size={32} />
              <h4 className="text-white font-semibold mb-2">Global Sentiment</h4>
              <p className="text-xs text-gray-400">News APIs, Twitter/X Social Volume, Fear & Greed Index</p>
            </div>
            <div className="bg-[#1A2133] p-6 rounded-xl border border-white/5 text-center group hover:border-[#00D9FF]/40 transition-all">
              <Database className="mx-auto text-[#00D9FF] mb-4 group-hover:scale-110 transition-transform" size={32} />
              <h4 className="text-white font-semibold mb-2">On-Chain Data</h4>
              <p className="text-xs text-gray-400">Whale Alerts, Exchange Inflows, Liquidation Maps</p>
            </div>
            <div className="bg-[#1A2133] p-6 rounded-xl border border-white/5 text-center group hover:border-[#00D9FF]/40 transition-all">
              <BarChart3 className="mx-auto text-[#00D9FF] mb-4 group-hover:scale-110 transition-transform" size={32} />
              <h4 className="text-white font-semibold mb-2">Price Action</h4>
              <p className="text-xs text-gray-400">Order Book Imbalance, Technical Indicators, Volatility</p>
            </div>
          </div>

          {/* Connector Arrows */}
          <div className="flex justify-center gap-16 md:gap-32 mb-4 text-gray-600">
             <div className="h-16 w-[1px] bg-gradient-to-b from-[#00D9FF]/50 to-transparent"></div>
             <div className="h-16 w-[1px] bg-gradient-to-b from-[#00D9FF]/50 to-transparent"></div>
             <div className="h-16 w-[1px] bg-gradient-to-b from-[#00D9FF]/50 to-transparent"></div>
          </div>

          {/* Layer 2: The Brain */}
          <div className="relative bg-gradient-to-r from-[#00D9FF]/10 to-[#00D4AA]/10 p-[1px] rounded-2xl mb-12 mx-auto max-w-2xl">
            <div className="bg-[#131826] rounded-2xl p-8 text-center relative overflow-hidden">
               <div className="absolute inset-0 bg-[#00D9FF]/5 animate-pulse"></div>
               <Brain className="mx-auto text-white mb-4 relative z-10" size={48} />
               <h3 className="text-2xl font-bold text-white mb-2 relative z-10">Neural Processing Core</h3>
               <p className="text-gray-400 text-sm relative z-10">
                 Transformer models analyze correlations across 50+ data points to calculate probability scores for potential trade setups.
               </p>
            </div>
          </div>

          {/* Connector Single */}
           <div className="flex justify-center mb-4">
             <div className="h-16 w-[1px] bg-gradient-to-b from-[#00D4AA] to-transparent"></div>
          </div>

          {/* Layer 3: Execution */}
          <div className="bg-[#0A0E1A] border border-[#00D4AA]/30 rounded-xl p-6 max-w-md mx-auto flex items-center gap-6">
            <div className="bg-white p-2 rounded">
              {/* Simple text logo for OKX */}
              <div className="font-black text-black text-lg tracking-tighter">OKX</div>
            </div>
            <div className="flex-1">
              <h4 className="text-white font-bold">Execution Engine</h4>
              <p className="text-xs text-gray-400">API signals sent instantly to your OKX account for execution.</p>
            </div>
            <div className="w-3 h-3 bg-[#00D4AA] rounded-full animate-ping"></div>
          </div>

        </div>
      </div>
    </section>
  );
};

const Performance = () => {
  return (
    <section id="performance" className="py-24 bg-[#0A0E1A]">
      <div className="container mx-auto px-6">
        <div className="flex flex-col md:flex-row justify-between items-end mb-12">
          <div>
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-2">Live Performance</h2>
            <p className="text-gray-400">Real-time tracking of all active AI strategies.</p>
          </div>
          <div className="flex items-center gap-2 text-[#00D4AA] text-sm mt-4 md:mt-0">
            <span className="w-2 h-2 bg-[#00D4AA] rounded-full animate-pulse"></span>
            System Operational
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="text-gray-500 text-sm border-b border-white/10">
                <th className="p-4 font-medium">Strategy Name</th>
                <th className="p-4 font-medium">Asset</th>
                <th className="p-4 font-medium">24h Change</th>
                <th className="p-4 font-medium">7d APY</th>
                <th className="p-4 font-medium">Total Profit</th>
                <th className="p-4 font-medium">Status</th>
              </tr>
            </thead>
            <tbody className="text-white">
              {[
                { name: "Alpha Predator", asset: "BTC/USDT", chg: "+2.4%", apy: "142%", profit: "+$12,404", status: "Active" },
                { name: "Alpha Predator", asset: "ETH/USDT", chg: "-0.8%", apy: "98%", profit: "+$8,291", status: "Active" },
                { name: "Delta Neutral", asset: "SOL/USDT", chg: "+0.2%", apy: "24%", profit: "+$1,102", status: "Active" },
                { name: "Trend Surfer", asset: "DOGE/USDT", chg: "+15.4%", apy: "310%", profit: "+$5,400", status: "Active" },
                { name: "Trend Surfer", asset: "ARB/USDT", chg: "+1.2%", apy: "45%", profit: "+$920", status: "Active" },
              ].map((row, idx) => (
                <tr key={idx} className="border-b border-white/5 hover:bg-white/5 transition-colors">
                  <td className="p-4 font-semibold">{row.name}</td>
                  <td className="p-4 text-gray-400">{row.asset}</td>
                  <td className={`p-4 ${row.chg.startsWith('+') ? 'text-[#00D4AA]' : 'text-red-400'}`}>{row.chg}</td>
                  <td className="p-4 text-[#00D9FF]">{row.apy}</td>
                  <td className="p-4">{row.profit}</td>
                  <td className="p-4"><span className="px-2 py-1 rounded bg-[#00D4AA]/10 text-[#00D4AA] text-xs">{row.status}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
};

const HowItWorks = () => {
  return (
    <section id="how-it-works" className="py-24 bg-[#0D1220]">
      <div className="container mx-auto px-6">
        <SectionTitle title="Start in 3 Minutes" subtitle="No coding required. Just connect and automate." />

        <div className="grid md:grid-cols-3 gap-8">
          {[
            { icon: Link, title: "1. Connect Exchange", desc: "Log in securely to your OKX account. Our system connects directly without requiring manual API key handling." },
            { icon: Activity, title: "2. Choose Strategy", desc: "Browse the marketplace and choose a strategy that matches your risk profile and asset preference." },
            { icon: Zap, title: "3. Subscribe & Start", desc: "Click subscribe, allocate your funds, and the AI will immediately begin executing trades." }
          ].map((step, idx) => (
            <div key={idx} className="relative p-8 rounded-2xl bg-[#131826] border border-white/5 z-10">
              <div className="absolute -top-4 -left-4 w-12 h-12 bg-[#00D9FF] text-[#0A0E1A] font-bold text-xl flex items-center justify-center rounded-xl shadow-lg shadow-cyan-500/20">
                {idx + 1}
              </div>
              <step.icon size={40} className="text-gray-600 mb-6 mt-2" />
              <h3 className="text-xl font-bold text-white mb-3">{step.title}</h3>
              <p className="text-gray-400 leading-relaxed">
                {step.desc}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState(null);

  return (
    <section className="py-24 bg-[#0A0E1A]">
      <div className="container mx-auto px-6 max-w-3xl">
        <SectionTitle title="Frequently Asked Questions" />

        <div className="space-y-4">
          {FAQS.map((faq, idx) => (
            <div key={idx} className="bg-[#131826] rounded-xl overflow-hidden border border-white/5">
              <button
                className="w-full p-6 text-left flex justify-between items-center text-white font-medium hover:bg-white/5 transition-colors"
                onClick={() => setOpenIndex(openIndex === idx ? null : idx)}
              >
                {faq.q}
                <ChevronDown className={`transition-transform ${openIndex === idx ? 'rotate-180' : ''}`} />
              </button>
              <div className={`px-6 text-gray-400 leading-relaxed transition-all duration-300 ease-in-out overflow-hidden ${openIndex === idx ? 'max-h-48 pb-6 opacity-100' : 'max-h-0 opacity-0'}`}>
                {faq.a}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

const Footer = () => {
  return (
    <footer className="bg-[#05070D] border-t border-white/10 pt-16 pb-8">
      <div className="container mx-auto px-6">
        <div className="grid md:grid-cols-4 gap-12 mb-12">
          <div className="col-span-1 md:col-span-2">
            <div className="text-2xl font-bold text-white tracking-wider flex items-center gap-2 mb-6">
              <div className="w-8 h-8 bg-gradient-to-br from-[#00D9FF] to-[#00D4AA] rounded flex items-center justify-center">
                <Brain size={20} className="text-[#0A0E1A]" />
              </div>
              INSAI
            </div>
            <p className="text-gray-500 max-w-sm">
              Democratizing institutional-grade trading strategies through artificial intelligence. Built for OKX.
            </p>
          </div>

          <div>
            <h4 className="text-white font-bold mb-4">Platform</h4>
            <ul className="space-y-2 text-gray-500">
              <li><a href="#" className="hover:text-[#00D9FF]">Strategies</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">Pricing</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">Live Performance</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">API Documentation</a></li>
            </ul>
          </div>

          <div>
            <h4 className="text-white font-bold mb-4">Legal</h4>
            <ul className="space-y-2 text-gray-500">
              <li><a href="#" className="hover:text-[#00D9FF]">Terms of Service</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">Privacy Policy</a></li>
              <li><a href="#" className="hover:text-[#00D9FF]">Risk Disclaimer</a></li>
            </ul>
          </div>
        </div>

        <div className="border-t border-white/5 pt-8 text-center text-gray-600 text-sm">
          &copy; {new Date().getFullYear()} INSAI Trading Technologies. All rights reserved.
          <br className="md:hidden" /> Cryptocurrency trading involves high risk. Invest responsibly.
        </div>
      </div>
    </footer>
  );
};

// --- Main App ---

export default function App() {
  return (
    <div className="min-h-screen bg-[#0A0E1A] text-white font-sans selection:bg-[#00D9FF] selection:text-[#0A0E1A]">
      <Navbar />
      <main>
        <Hero />
        <Performance />
        <Strategies />
        <AIProcess />
        <HowItWorks />
        <FAQ />
      </main>
      <Footer />
    </div>
  );
}
